name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html

            git pull origin main

            cd frontend
            npm install
            npm run build

            # Remove old files from the web root (optional, but keeps things clean)
            sudo rm -rf /var/www/html/*
            
            # Copy new build files to web root
            sudo cp -r dist/* /var/www/html/

            # Restart Apache (optional but recommended)
            sudo systemctl restart apache2
          EOF
